---
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/eclipse-builds@eclipse-362422.iam.gserviceaccount.com'
steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    #!/usr/bin/env bash
    docker pull "${_IMAGE_NAME}" || exit 0
  env:
  - '_IMAGE_NAME=${_IMAGE_NAME}'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_IMAGE_NAME}'
  - '--cache-from'
  - '${_IMAGE_NAME}'
  - '-f'
  - 'Dockerfile'
  - '.'
  timeout: 3600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_NAME}'
  - '--image'
  - '${_IMAGE_NAME}'
  - '--region'
  - '${_LOCATION}'
images:
- '${_IMAGE_NAME}'
substitutions:
  _IMAGE_NAME: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_NAME}:latest'
  _LOCATION: us-central1
  _NAME: chain-registry
  _REPOSITORY: eclipse-docker-apps
options:
  dynamic_substitutions: true
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
