//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[serde(crate = "rocket::serde")]
#[sea_orm(table_name = "evm_chain")]
pub struct Model {
    #[sea_orm(column_name = "chainId")]
    #[sea_orm(primary_key)]
    pub chain_id: String,
    pub rpc_urls: Vec<String>,
    pub block_explorer_urls: Vec<String>,
    pub icon_urls: Vec<String>,
    pub chain_name: String,
    pub native_currency_name: String,
    pub native_currency_decimals: i32,
    pub native_currency_symbol: String,
    pub data_availability: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
